services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Kernel.php'

    App\Infrastructure\ApiClient\DebrickedClient:
        arguments:
            $userName: '%env(DEBRICKED_API_USERNAME)%'
            $password: '%env(DEBRICKED_API_PASSWORD)%'
            $apiUrl: '%env(DEBRICKED_API_URL)%'
            $projectDir: '%kernel.project_dir%/public'

    App\Infrastructure\DataProvider\CollectionDataProvider:
        tags: [ 'api_platform.collection_data_provider' ]

    App\Infrastructure\Doctrine\Listener\NewJobListener:
        tags: [ doctrine.orm.entity_listener ]

    App\Infrastructure\Utils\InfiniteRetryStrategy:
        arguments:
            $waitingTimeInMilliseconds: '%env(WORKERS_WAITING_TIME_INT_MILLISECONDS)%'
